product/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "product"

urlpatterns = [
    path("", views.index, name="index"),

]

pucca/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("product.urls", namespace="product")),
        
        path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
        path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "PROJECT Administration"
admin.site.site_title = "PROJECT Admin Portal"
admin.site.index_title = "Welcome to PROJECT Admin Portal"

product/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    image = models.ImageField(upload_to="products/img")  
    title = models.CharField(max_length=20)
    offer = models.IntegerField(null=True,blank=True)
    link = models.URLField()

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = ("PRODUCT")
        verbose_name_plural = ("PRODUCT") 

product/views.py
from django.shortcuts import render
from . models import Product

# Create your views here.

def index(request):
    products = Product.objects.all()
    context = {
         "products":products,
    }
    return render(request,"web/index.html", context)

templates/web/index.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block title %}Pucca Deals{% endblock %}

{% block content %}
<section class="container text-center">
  <div class="circle">
    <a href="{% url "product:index" %}"><img src="{% static "web/image/banner.jpg" %}" alt="Logo"></a>
  </div>
  <div class="text-effect">
    <h2> PUCCA DEALS</h2> <br>
    <p>Pucca Deals is a participant of Amazon LLC Associate Program which is an affiliate advertising program designed for website owners to earn fees by advertising and linking to Amazon.</p><br>
  </div>
  <div class="row mb-5">
    {% for product in products %}
    <div class="col-lg-4 col-md-6 col-sm-6 col-6 rts">
      <div class="card">
        <div class="ec-product-inner">
          <div class="ec-pro-image">
            <a href="{{ product.link }}"><div class="ribbon">#{{product.offer}}</div></a>
            <a href="{{ product.link }}" class="image"><img class="main-image" src="{{product.image.url}}" alt="Product" /></a>
          </div>
        </div>
        <div class="card-body">
          <h5 class="card-title"><a href="{{ product.link }}">{{product.title}}</a></h5>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  
</section>
{% endblock %}

{% block css_plugins %}{% endblock %}
{% block js_plugins %}{% endblock %}

{% block javascript %}
<script>
  console.log("This will run only in index.html")
</script>
{% endblock %}

templates/web/partials/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Title{% endblock %}</title>
    {% block css_plugins %}{% endblock %}
    <link rel="stylesheet" href="{% static 'web/style.css' %}" />
    <link rel="shortcut icon" href="{% static "web/image/banner.jpg" %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    {% block stylesheet %}{% endblock %}
</head>
<body>
    <style>
        @media (min-width: 1400px) {
          .container, .container-lg, .container-md, .container-sm, .container-xl, .container-xxl {
            max-width: 1079px;
          }
        }
    </style>

    {% block content %}

    {% endblock %}
    
    {% block js_plugins %}{% endblock %}
    <script src="{% static 'web/js/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    {% block javascript %}{% endblock %}
</body>
</html>